### ISSUE TITLE
Error handling Dispatch (NullReferenceException)

### ISSUE THREAD

**Issue by TheOnly8Z** [chiyadev/MudaeFarm#14]
This error popped up a few times, but I was unable to replicate what caused it.
```
[erro] Error handling Dispatch (TYPING_START): System.NullReferenceException: Object reference not set to an instance of an object.
[erro]    at Discord.WebSocket.SocketGuildChannel.GetPermissionOverwrite(IRole role)
[erro]    at Discord.Permissions.ResolveChannel(IGuild guild, IGuildUser user, IGuildChannel channel, UInt64 guildPermissions)
[erro]    at Discord.WebSocket.SocketTextChannel.GetUser(UInt64 id)
[erro]    at Discord.WebSocket.DiscordSocketClient.<ProcessMessageAsync>d__112.MoveNext()
```

**Comment by phosphene47** [comment]
This is actually due to using an outdated version of Discord library (Discord.Net), not MudaeFarm itself.
We can't fix this but we can ignore the error and not log it at all.

**Comment by phosphene47** [comment]
Related: #4
