### ISSUE TITLE
Channel doesn't being monitored - Wish chapters doesn't match.

### ISSUE THREAD

**Issue by NotVIPerson** [chiyadev/MudaeFarm#223]
**Part 1:**
Hello,
I already see it another threads and more people have same problem months ago.
But idk if is already fix on 4.0.5 or not.

My problem is:
**_Working_**: Ranks displayed during rolls: **disabled** <-> ($togglerolls) The log **can** be get.
Ignoring character 'Tao (AnY) (Akatsuki no Yona)' in channel '???mudae' (XXXXXXXXXXXXXXXXXX, server 'XXXXXX') because they are not wished.

**_Not working_**: Ranks displayed during rolls: **enable** <-> ($togglerolls) The log **can't** be get.

**_Is there any changes I can make and recompile the code to make it work?_**
How can I do fix it? Any solution?

**Part 2:**
I created a new server and put the Mudae bot for testing, there it works to capture the log of $w
But even using the names exactly as they appear in $im he never redeems when it appears on the screen.
I've read all the topics talking about this topic, tried all the tips and none worked.
In the debug log the names look like this:

> dbug: MudaeFarm.MudaeClaimCharacterFilter[0]
>       Loaded character wishlist: {"items":[{"name":"^Morgiana$"},{"name":"^Denki\\s+Kaminari$"},{"name":"^Juvia\\s+Lockser$"},{"name":"^Kizuna\\s+AI$"},{"name":"^Tanya\\s+Degurechaff$"},{"name":"^Nyan\\s+Cat$"},{"name":"^Shinoa\\s+Hiiragi$"},{"name":"^Tetsurou\\s+Kuroo$"},{"name":"^Edward\\s+Elric$"},{"name":"^Itsuki\\s+Nakano$"},{"name":"^Chizuru\\s+Ichinose$"},{"name":"^Mikan\\s+Tsumiki$"},{"name":"^Merlin$"},{"name":"^Shouta\\s+Aizawa$"},{"name":"^Leafa$"},{"name":"^Doge$"},{"name":"^Yui\\s+Yuigahama$"},{"name":"^Eren\\s+Jaeger$"},{"name":"^Kenma\\s+Kozume$"},{"name":"^Bunny\\s+Girl\\s+Senpai$"}]}

**A piece of log:**
_Sometimes an exception appears with the directory from which the release was compiled, but not always, even when it runs without any warning, the problems remain the same._

> 2020-09-25T15:33:45.9804379-03:00  [INF] Selected profile 'M'. (6981353a)
> 2020-09-25T15:33:46.1827719-03:00  [INF] [Gateway] Connecting... (3a91e634)
> 2020-09-25T15:33:46.2329801-03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
> 2020-09-25T15:33:46.2353577-03:00  [INF] Hosting environment: "Production" (c3307c92)
> 2020-09-25T15:33:46.2354453-03:00  [INF] Content root path: "D:\Mudaefarm_4.0.5" (b5d60022)
> 2020-09-25T15:33:47.5526448-03:00  [INF] [Gateway] Identifying... (37d6c6c9)
> 2020-09-25T15:33:48.3089671-03:00  [INF] [Gateway] Successfully identified. (271fd42f)
> 2020-09-25T15:33:48.4857877-03:00  [INF] [Gateway] Awaiting sync for 4 guilds. (9c808232)
> 2020-09-25T15:33:48.5157997-03:00  [WRN] Logged in as M#0101. (afb246d5)
> 2020-09-25T15:33:48.5286594-03:00  [INF] Using configuration server 'Matrix' (758132XXXX845151XX). (0e39c3f3)
> 2020-09-25T15:33:50.3943581-03:00  [INF] Loaded all configuration in 1.87s. (821704b4)
> 2020-09-25T15:33:50.3978575-03:00  [WRN] MudaeFarm is up and running! MudaeFarm will shut down when you close this window. Refer to https://github.com/chiyadev/MudaeFarm#configuration for the configuration guide. For additional logging information, restart MudaeFarm with a --verbose CLI argument. (a1ec1f79)
> 2020-09-25T15:33:51.2942349-03:00  [INF] Sent roll 1 of batch 0 in channel '💋┆mudae' (5950XXXX640022XXXX). (06296b08)
> 2020-09-25T15:33:52.6388369-03:00  [INF] Sent roll 2 of batch 0 in channel '💋┆mudae' (5950XXXX640022XXXX). (e42e5664)
> 2020-09-25T15:33:54.0671386-03:00  [INF] Sent roll 3 of batch 0 in channel '💋┆mudae' (5950XXXX640022XXXX). (89350696)
> 2020-09-25T15:33:57.1141726-03:00  [WRN] Sent command '$wa' in channel '💋┆mudae' (5950XXXX640022XXXX) but did not receive expected Mudae response. (dd2ab66a)
> 2020-09-25T15:33:57.2236595-03:00  [WRN] Could not roll '$wa' in channel '💋┆mudae' (5950XXXX640022XXXX). (d137629a)
> System.Threading.Tasks.TaskCanceledException: A task was canceled.
>    at MudaeFarm.MudaeCommandHandler.ReceiveAsync(DiscordClient client, IChannel channel, CancellationToken cancellationToken) in C:\Projects\MudaeFarm\MudaeFarm\MudaeCommandHandler.cs:line 106
>    at MudaeFarm.MudaeCommandHandler.ReceiveAsync(DiscordClient client, IChannel channel, CancellationToken cancellationToken) in C:\Projects\MudaeFarm\MudaeFarm\MudaeCommandHandler.cs:line 106
>    at MudaeFarm.MudaeCommandHandler.SendAsync(IMessageChannel channel, String command, CancellationToken cancellationToken) in C:\Projects\MudaeFarm\MudaeFarm\MudaeCommandHandler.cs:line 47
>    at MudaeFarm.MudaeRoller.RunRollAsync(DiscordClient client, IMessageChannel channel, CancellationToken cancellationToken) in C:\Projects\MudaeFarm\MudaeFarm\MudaeRoller.cs:line 149
> 2020-09-25T15:35:06.6366250-03:00  [INF] Application is shutting down... (90f52c38)
> 2020-09-25T15:35:06.6424878-03:00  [INF] [Gateway] Disconnecting... (080a2550)

![1](https://user-images.githubusercontent.com/71900969/94307122-8c04a980-ff4a-11ea-9b92-71966286f337.png)

**Comment by phosphene47** [comment]
Thanks for the detailed report.

> Part 1:

From what I gathered so far, there seems to be a difference in the format of character messages in rankings-enabled and -disabled servers. [This](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/MudaeClaimer.cs#L80) is the method which I've deduced to be problematic. (If you are able to find a fix, please do submit a pull request!)

> Part 2:

I think the number of backslashes before `s+` is causing this issue. Wishlist items are converted to regexes in [this method](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/DiscordConfigurationSource.cs#L189), which replaces space literals `\ ` with space expressions `\s+`. Thus I would expect that the log JSON would output `"^Denki\\s+Kaminari$"` as the backslash gets escaped, but instead it shows `"^Denki\s+Kaminari$"` including a unicode character `"\s"` not a regex `"\\s"`.

> A piece of log:

The `TaskCanceledException` log worries me. There are multiple open issues about this exception, but I haven't been able to find out exactly what causes this. I think there is a problem with the [channel roller task initialization](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/MudaeRoller.cs#L51) code, but then again cancellation state is checked [by the rolling loop](https://github.com/chiyadev/MudaeFarm/blob/master/MudaeFarm/MudaeRoller.cs#L131) so `TaskCanceledException` should not be occurring unless you remove a roll channel in the configuration while the bot is still sending the roll message.

There are no workarounds that I'm aware of, unfortunately.

> Some visual problem:

MudaeFarm wasn't able to parse Mudae's response which was not English `**S_____**, 2 usos restantes.` This is intentionally not supported because I don't know Spanish (sorry if I got this wrong). There is an open [issue](https://github.com/chiyadev/MudaeFarm/issues/67) requesting support for other languages.

**Comment by Biop6** [comment]
I realized that he doesn't use the right roll if the mudae is not in English, if he uses any other language, he rotates the last two and the next ones are random, would I be able to edit myself to recognize another language?

**Comment by phosphene47** [comment]
> I realized that he doesn't use the right roll if the mudae is not in English, if he uses any other language, he rotates the last two and the next ones are random, would I be able to edit myself to recognize another language?

I don't really understand what you're trying to say, but you can always edit the code and recompile the bot as you see fit.
